CXX=g++
#CXX=clang++
CXXFLAGS=-std=c++11 -Wall -Wextra
SOURCES=main.cxx ./CLR/AssemblyData.cxx ./CLR/CliMetadataTableIndex.cxx 

picovm: main.cxx
	-mkdir build
	$(CXX) $(CXXFLAGS) $(SOURCES) -o build/picovm
clean:
	-rm -f ./build/picovm 2> /dev/null
	-rm -r build 2> /dev/null
