ifeq (${USE_CLANG}, 1)
    CXX=clang++
else
    CXX=g++
endif

CXXFLAGS=-std=c++11 -Wall -Wextra

EXEC=picovm
SOURCES= \
         main.cxx \
         CLR/AssemblyData.cxx \
         CLR/CLIMetadataTableIndex.cxx \
         CLR/AssemblyReader.cxx
OBJECTS=$(SOURCES:.cxx=.o)

all: $(EXEC)

$(EXEC): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cxx
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
	-rm -f picovm
	-rm -f *.o
	-rm -f CLR/*.o